### ISSUE TITLE
Repeated read gives always the same value

### ISSUE THREAD

**Issue by piotromt** [OpenBluetoothToolbox/python_simpleble#8] opened 2022-05-22 23:26 UTC
It seems that reading value from characteristic from peripheral never gets updated during one connection, multiple reads during the same connection always give me the same value, even when the characteristic is updated on the service side. I did a test, I created a peripheral with service with 2 text characteristics, A for writing and B for reading. On the service side, when A is written , B is updated. When I do the the connection to this peripheral and then the sequence: write - read - write different value - read, the second read gives me the value from the first read, it never gets updated. When I disconnect from peripheral and connect again, read gives me updated second value. Is this a "feature" or the bug?

**Comment by piotromt** [comment] 2022-05-24 00:07
I can see in the code in PeripheralBase.cpp:
auto result = async_get(gatt_characteristic.ReadValueAsync());
The windows documentation says that in this case value will be taken from the cache. So it is a "feature" and if I don't like this behaviours the only option is to change the code and recompile... 

https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattcharacteristic.readvalueasync?view=winrt-22000

**Comment by kdewald** [comment] 2022-05-24 15:20
Hey @piotromt, thanks for the report!
Please don't jump to assumptions about anything being a feature or a bug.

The intended behavior of this function is to perform a new read every time the function is called, so clearly this falls into the "bug" category. I'll look at it and fix it as soon as I can.

**Comment by piotromt** [comment] 2022-05-24 15:59
I've actually did an experiment. Took your code for both SimpleBLE and python bindings, and added "read_not_cached" function which is exact copy of your read function with one change: added Devices::Bluetooth::BluetoothCacheMode::Uncached in gatt_characteristic.ReadValueAsync call. Then brought this function up to python.
Now my new function works as expected: it reads values from the source each time.
You might consider keeping the old function as it was and adding a new one, or adding a parameter to the old one.

// Read the value.
    auto result = async_get(
        gatt_characteristic.ReadValueAsync(Devices::Bluetooth::BluetoothCacheMode::Uncached));

On separate note, after I did my change, the function "write_command" (which I was using before) no longer works - it displayed the error: The requested operation is not supported. But write_request started working. With your original code it was opposite....

And finally - the whole round trip - writing the characteristic and reading it takes around 200ms. I did similar operation write and read between 2 Arduinos and the whole round trip was 45ms. Why could it be so much slower?
I use Win10, some Bluetooth adapter and Arduino Nano33 BLE as peripheral.

**Comment by kdewald** [comment] 2022-05-24 16:22
Thanks for the uncached read snippet!

```
// Read the value.
auto result = async_get(
gatt_characteristic.ReadValueAsync(Devices::Bluetooth::BluetoothCacheMode::Uncached));
```

There was a bug before where `write_command` and `write_request` were swapped, that might be the cause. I also made a few of these checks a lot more explicit.

> And finally - the whole round trip - writing the characteristic and reading it takes around 200ms. I did similar operation write and read between 2 Arduinos and the whole round trip was 45ms. Why could it be so much slower?

Your computer might be selecting a much longer connection interval vs the Arduino. You can tweak them on the Arduino side in whatever settings you use for the `connection interval` parameter.

**Comment by piotromt** [comment] 2022-05-24 16:37
There seems to be more functions that read from cache depending on the parameter. See the link:
https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothcachemode?view=winrt-22000
You might consider some additional changes.

In terms of speed, my "fast architecture" was: Python <-> pyserial <- serial cable -> Arduino Nano 33 Ble <- > BLE <-> Another Arduino Nano 33 BLE
My slow architecture is: Python <- your (very nice) library ->  BLE <-> Arduino Nano 33 BLE

I can see in the code for read you do:
GattCharacteristic gatt_characteristic = _fetch_characteristic(service, characteristic);

Is it possible that each time I do read, the _fetch_characteristic goes to the board via BLE and checks the characteristic directly? This time going to some cache would be more appropriate.

**Comment by kdewald** [comment] 2022-05-24 16:40
No, `_fetch_characteristic` just returns a reference to the underlying WinRT object.

I think what you're dealing with has to do with this: https://www.novelbits.io/ble-connection-intervals/

**Comment by piotromt** [comment] 2022-05-24 22:41
It could indeed be the case. 
It seems that BLE speed is quite a complex problem with many variables. When I have 2 chips from the same manufacturer talking to each other it could be quite fast, otherwise all these problems with connection interval/number of packets per interval etc may cause delays.
What I might say is that connection between Windows and my Arduino chip is much more reliable but also much slower (around 7 times slower). On Windows I never get problems with discovering characteristics (what happens in case of 2 Arduinos talking to each other) and read-write is always successfully (unlike Arduinos where it occasionally fails and I have to repeat the read or write). 
Because I need message turn-around time less then 55 ms, I might have to stick with PC -> serial cable -> Arduino -> BLE -> Arduino and won't use your very nicely written library after all :-)

**Comment by piotromt** [comment] 2022-05-25 15:28
Last night I decided to give it a last try, I set the interval to the shortest possible for both min and max and .... and ...  tada! 

Roundtrip in around 40ms, 20ms for write and 20 for read :-)

So I WILL be using your library. For now I use compiled version where I change the read function, when you update your package, I will take it.
Thank you for all the help!

**Comment by piotromt** [comment] 2022-05-26 22:40
Now it all works OK with one connection. 
What I need really is to connect to 2 peripherals. I tested it many times and found that connection to the first peripheral is very fast (less than e second), connection to the second one is slow (could be 5 seconds). 
I have 2 identical boards with identical programs and the only difference is the the address which I use to identify them. 
I change the order of the connections back and forth between the boards (so it is not a specific board problem) and the second connection is always slower.

I also change scenarios:

- Scenario A. connection 1, connection 2, disconnection 1, disconnection 2 - in this scenario connection 2 does not return any error, but peripheral_2.is_connected() returns false so the second connection never works. So it seems that I cannot have two open connections at the same time.
- Scenario B. connection 1, disconnection 1, connection 2, disconnection 2 - in this scenario both connections work most of the time, sometimes the second one fails (with "RuntimeError: Caught an unknown exception!"), but the board actually records the connection and thinks it is connected.

What could be the reason for these behaviours? Any ideas?
The simple code I use is shown below:

`import simplepyble
import time
from datetime import datetime, timedelta

if __name__ == "__main__":
    adapters = simplepyble.Adapter.get_adapters()

    if len(adapters) == 0:
        print("No adapters found")
        
    adapter = adapters[0]

    print(f"Selected adapter: {adapter.identifier()} [{adapter.address()}]")

    adapter.set_callback_on_scan_start(lambda: print("Scan started."))
    adapter.set_callback_on_scan_stop(lambda: print("Scan complete."))
    adapter.set_callback_on_scan_found(lambda peripheral: print(f"Found [{peripheral.identifier()}] [{peripheral.address()}]"))

    # Scan for 5 seconds
    adapter.scan_for(1000)
    peripherals = adapter.scan_get_results()

    # Query the user to pick a peripheral0
    
    print("")
    peripheral_1_idx = None
    peripheral_2_idx = None
    for i, peripheral in enumerate(peripherals):
        
        addr = peripheral.address()
        print(f"{i}: {peripheral.identifier()} [{addr}]")
        if addr == "addres of the first board here":
            peripheral_1_idx = i
        if addr == "addres of the first board here"":
            peripheral_2_idx = i

    print(f"Perip 1: idx {peripheral_1_idx}")
    print(f"Perip 2: idx {peripheral_2_idx}")
        
    peripheral_1 = peripherals[peripheral_1_idx]
    peripheral_2 = peripherals[peripheral_2_idx]

    print(f"Connecting to 1: {peripheral_1.identifier()} [{peripheral_1.address()}]")    
    print(f"Connecting to 2: {peripheral_2.identifier()} [{peripheral_2.address()}]")
    
   
    peripheral_2.connect()    
    if peripheral_2.is_connected():
        print("Connected 2 YES")
    else:
        print("Connected 2 NOT")
        
    peripheral_2.disconnect()
    print("DisConnected 2")        
        
    peripheral_1.connect()
    if peripheral_1.is_connected():
        print("Connected 1 YES")
    else:
        print("Connected 1 NOT")
            
    peripheral_1.disconnect()
    print("DisConnected 1")`

**Comment by kdewald** [comment] 2022-07-13 06:36
Original issue has been fixed in SimpleBLE, a new release will be made soon.

**Closed by kdewald** 2022-07-13 06:36 UTC
